"use client";

import React from "react";
import {
  ClipboardList,
  FileText,
  Handshake,
  Briefcase,
  Home,
  Building2,
  Trophy,
  Star,
  Crown,
  Target,
  BookOpen,
  Zap,
  Flame,
  CheckCircle2,
  Circle,
  Lock,
  Lightbulb,
  XCircle,
  GraduationCap,
  Video,
  BarChart3,
  Puzzle,
  CalendarDays,
  MessageSquare,
  Save,
  PartyPopper,
  AlertTriangle,
  TrendingUp,
  Scale,
  Calculator,
  type LucideIcon,
  Medal,
  Dumbbell,
  Cake,
  Newspaper,
  Printer,
  Globe,
  Camera,
  Banknote,
  Pen,
  Flag,
  KeyRound,
  DoorOpen,
  Megaphone,
  Unlock,
  Hourglass,
  Sparkles,
  Shield,
  Gift,
  Ticket,
  Pin,
  Palette,
  Brain,
  Bell,
  ShoppingCart,
  Smartphone,
  Gem,
  Swords,
  Tag,
  CreditCard,
  Landmark,
  Map,
  Search,
  ThumbsUp,
  FolderOpen,
  Hash,
  Clock,
  ScrollText,
  CircleDollarSign,
  Undo2,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "📋": ClipboardList,
  "📝": FileText,
  "🤝": Handshake,
  "💼": Briefcase,
  "🏠": Home,
  "🏢": Building2,
  "🏆": Trophy,
  "⭐": Star,
  "👑": Crown,
  "🎯": Target,
  "📚": BookOpen,
  "⚡": Zap,
  "🔥": Flame,
  "✅": CheckCircle2,
  "✓": CheckCircle2,
  "○": Circle,
  "🔒": Lock,
  "💡": Lightbulb,
  "❌": XCircle,
  "🎓": GraduationCap,
  "🎬": Video,
  "📊": BarChart3,
  "🧩": Puzzle,
  "📅": CalendarDays,
  "💬": MessageSquare,
  "💾": Save,
  "🎉": PartyPopper,
  "⚠️": AlertTriangle,
  "📈": TrendingUp,
  "⚖️": Scale,
  "🧮": Calculator,
  "💰": CircleDollarSign,
  "📱": Smartphone,
  "🏡": Home,
  "💎": Gem,
  "⚔️": Swords,
  "🏁": Flag,
  "✍️": Pen,
  "⏳": Hourglass,
  "🔓": Unlock,
  "📜": ScrollText,
  "🔑": KeyRound,
  "📣": Megaphone,
  "🚪": DoorOpen,
  "⏰": Clock,
  "🔢": Hash,
  "📁": FolderOpen,
  "👍": ThumbsUp,
  "🔎": Search,
  "📄": FileText,
  "💸": Banknote,
  "💌": MessageSquare,
  "📸": Camera,
  "🌐": Globe,
  "🗺️": Map,
  "🎂": Cake,
  "📰": Newspaper,
  "📷": Camera,
  "📢": Megaphone,
  "🏷️": Tag,
  "💳": CreditCard,
  "🏦": Landmark,
  "🖨️": Printer,
  "💪": Dumbbell,
  "✨": Sparkles,
  "🌟": Sparkles,
  "👏": Handshake,
  "🏗️": Building2,
  "🗝️": KeyRound,
  "🛡️": Shield,
  "📌": Pin,
  "🎨": Palette,
  "🧠": Brain,
  "🔔": Bell,
  "🛒": ShoppingCart,
  // "🪧": Signpost,
  "🎁": Gift,
  "🎟️": Ticket,
  "🎫": Ticket,
  "🎖️": Medal,
  "🥇": Trophy,
  "🥈": Medal,
  "🥉": Medal,
  "↩": Undo2,
};

interface EmojiIconProps {
  emoji: string;
  className?: string;
  fallbackClassName?: string;
}

export function EmojiIcon({ emoji, className = "h-4 w-4", fallbackClassName }: EmojiIconProps) {
  const Icon = MAP[emoji];
  if (Icon) {
    return <Icon className={className} aria-hidden="true" />;
  }
  return (
    <span className={fallbackClassName} aria-hidden="true">
      {emoji}
    </span>
  );
}
